services:
  - type: web
    name: tarteeb-abu-alyaa
    runtime: docker
    plan: free
    branch: main
    autoDeployTrigger: checksPass
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
